import Image from 'next/image';
import Link from 'next/link';
import { FaReact, FaStripeS, FaHtml5, FaCss3Alt, FaJsSquare, FaGithub, FaLinux, FaNodeJs } from 'react-icons/fa';
import { SiDigitalocean, SiNextdotjs, SiOpenai, SiMicrosoftoffice, SiGoogleanalytics, SiUbuntu, SiGoogle, SiNginx } from 'react-icons/si';
import styles from '../styles/projects.css';

function Projects() {
  const projects = [
    {
      id: 1,
      title: "Renaissance Resumes",
      description: "Renaissance Resumes is an innovative online resume builder that leverages advanced language learning models (LLM), specifically GPT technology, to generate customized resumes based on user prompts. The platform allows users to refine and tweak the autogenerated content before purchasing and downloading the final product in a ready-to-use DOCX format.",
      imageUrl: "/images/renaissanceLogo.svg",
      link: "https://renaissanceresumes.com",
      technologies: [
        { name: 'ReactJS', icon: <FaReact /> },
        { name: 'Next.js', icon: <SiNextdotjs />  }, // Assuming you use React's icon for Next.js as well
        { name: 'DigitalOcean', icon: <SiDigitalocean /> },
        { name: 'Ubuntu', icon: <SiUbuntu /> },
        { name: "Linux", icon: <FaLinux /> },
        { name: 'OpenAI API', icon: <SiOpenai /> },
        { name: 'Stripe API', icon: <FaStripeS /> },
        { name: 'HTML', icon: <FaHtml5 /> },
        { name: 'JavaScript', icon: <FaJsSquare /> },
        { name: 'Node.js', icon: <FaNodeJs /> },
        { name: 'ES6', icon: <FaJsSquare /> },
        { name: 'CSS', icon: <FaCss3Alt /> },
        { name: "Google Analytics", icon: <SiGoogleanalytics /> },
        { name: "Google Marketing Platform", icon: <SiGoogle /> }
        
      ],
      features: "LLM-Guided Content Creation, Interactive Editing Interface, Secure Payment Integration, Direct Download",
    },
    {
        id: 2,
        title: "Munt's Landscaping",
        description: "Munt's Landscaping offers residential and commercial landscaping services. I developed a website that not only showcases their services through dedicated landing pages but also optimizes each page for SEO to improve search engine rankings. A key feature of the site is the user-friendly estimate request modal, designed to enhance user experience and increase customer engagement.",
        imageUrl: "/images/muntsLogo.svg",
        link: "https://muntslandscaping.ca",
        technologies: [
            { name: 'ReactJS', icon: <FaReact /> },
            { name: 'DigitalOcean', icon: <SiDigitalocean /> },
            { name: 'Ubuntu', icon: <SiUbuntu /> },
            { name: "Linux", icon: <FaLinux /> },
            { name: 'HTML', icon: <FaHtml5 /> },
            { name: 'JavaScript', icon: <FaJsSquare /> },
            { name: 'Node.js', icon: <FaNodeJs /> },
            { name: 'ES6', icon: <FaJsSquare /> },
            { name: 'CSS', icon: <FaCss3Alt /> },
            { name: "Google Analytics", icon: <SiGoogleanalytics /> },
            { name: "Google Marketing Platform", icon: <SiGoogle /> }
        ],
        features: "Created SEO-optimized landing pages for each service offered to enhance search engine visibility. Integrated a user-friendly estimate request modal to streamline customer interactions and increase conversions. The website has significantly boosted the business, increasing customer inquiries and improving online visibility."
      },
      
      {
        id: 3,
        title: "DeJong Health Consulting",
        description: "DeJong Health Consulting offers personalized dietitian services through a virtual platform, seamlessly connecting clients to health professionals. The service integrates external booking and appointment management systems to facilitate client interactions and service delivery.",
        imageUrl: "/images/DeJongHealthLogo.svg",
        link: "https://dejonghealthconsulting.com",
        technologies: [
            { name: 'ReactJS', icon: <FaReact /> },
            { name: 'Next.js', icon: <SiNextdotjs />  }, // Assuming you use React's icon for Next.js as well
            { name: 'DigitalOcean', icon: <SiDigitalocean /> },
            { name: 'Ubuntu', icon: <SiUbuntu /> },
            { name: "Linux", icon: <FaLinux /> },
            { name: 'HTML', icon: <FaHtml5 /> },
            { name: 'JavaScript', icon: <FaJsSquare /> },
            { name: 'Node.js', icon: <FaNodeJs /> },
            { name: 'ES6', icon: <FaJsSquare /> },
            { name: 'CSS', icon: <FaCss3Alt /> },
            { name: "Google Analytics", icon: <SiGoogleanalytics /> },
            { name: "Google Marketing Platform", icon: <SiGoogle /> }
        ],
        "features": "Integrated with an external service for booking and virtual appointments, facilitating seamless interactions between dietitians and clients. Configured advanced tracking and marketing strategies using Google Analytics and Google Marketing to optimize user engagement and service outreach."
      },
      
      {
        id: 4,
        title: "Fusion Doctor",
        description: "Fusion Doctor features a custom-developed website for a mobile bartending service in the Greater Toronto Area, showcasing advanced web development and system integration skills. This project highlights my ability to deliver robust, user-friendly solutions that enhance business operations and customer engagement.",
        imageUrl: "/images/fusionDrLogo.svg",
        link: "https://fusiondr.ca",
        technologies: [
            { name: 'ReactJS', icon: <FaReact /> },
            { name: 'Next.js', icon: <SiNextdotjs />  }, // Assuming you use React's icon for Next.js as well
            { name: 'DigitalOcean', icon: <SiDigitalocean /> },
            { name: 'Ubuntu', icon: <SiUbuntu /> },
            { name: "Linux", icon: <FaLinux /> },
            { name: 'HTML', icon: <FaHtml5 /> },
            { name: 'JavaScript', icon: <FaJsSquare /> },
            { name: 'Node.js', icon: <FaNodeJs /> },
            { name: 'ES6', icon: <FaJsSquare /> },
            { name: 'CSS', icon: <FaCss3Alt /> },
        ],
        features: "Developed using modern web technologies including Next.js and Node.js, this website integrates a seamless online booking system utilizing EmailJS. It features responsive design, cross-browser compatibility, and is hosted on a Linux server via DigitalOcean, ensuring reliable and secure access."
      }
      
  ];

  return (
    <div className="projectsContainer" id='projects'>
      {projects.map(project => (
        <div key={project.id} className="projectRow">
          <Link href={project.link} passHref>
              <div className="projectImage">
                <Image src={project.imageUrl} alt={project.title} width={200} height={120} layout="responsive" />
              </div>
          </Link>
          <div className="projectInfo">
    <h3 style={{textAlign: 'center'}}>{project.title}</h3>
    <p style={{padding:'20px', textIndent:'50px'}}>{project.description}</p>
    <div className="technologyList">
        {project.technologies.map(tech => (
            <div key={tech.name} className="technologyItem">
                {tech.icon}
                <div style={{ fontSize: '14px', margin: '5px' }}>{tech.name}</div>
            </div>
        ))}
    </div>
    {project.features && <p style={{textAlign: 'center'}}><strong>Key Features:</strong> {project.features}</p>}
</div>

        </div>
      ))}
    </div>
  );
}

export default Projects;



